language: objective-c

script: 
- xctool -project TestProject/Objective-C-Regex-Categories.xcodeproj -scheme Objective-C-Regex-Categories -sdk iphonesimulator clean build test -freshSimulator -freshInstall